# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.5
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

## Dependencies Property
jei_version=15.8.2.26
patchouli_version=1.20.1-84-FORGE
patchouli_version_range=[1.20.1-84-FORGE,)

## Mod Properties
mod_id=yeastnfeast
mod_name=Yeast 'n Feast
mod_license=MIT
mod_version=0.1.41-1.20.1+forge
mod_group_id=net.grapes.yeastnfeast
mod_authors=Grapes Studios
mod_description=A mod that allows you to make baked goods, or brew different types of mead with new fruits, spices and herbs.